// 前端筆記側邊欄設定

const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      label: "前端筆記",
      id: "webnote",
    },
    {
      type: "category",
      label: "套件",
      items: [
        {
          type: "autogenerated",
          dirName: "packages",
        },
      ],
    },
  ],
};

module.exports = sidebars;
